[package]
name = "backupper"
version = "0.1.0"
edition = "2021"
authors = ["Kirill <k@kunansy.ru>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10.0"
chrono = "0.4"
